a3p1Client1 : a3p1Client1.c
	gcc a3p1Client1.c -pthread -o a3p1Client1

a3p2Client1 : a3p2Client1.c
	gcc a3p2Client1.c -pthread -o a3p2Client1

a3p3Client1 : a3p3Client1.c
	gcc a3p3Client1.c -pthread -o a3p3Client1

a3p2Client2 : a3p2Client2.c
	gcc a3p2Client2.c -pthread -o a3p2Client2

a3p3Client2 : a3p3Client2.c
	gcc a3p3Client2.c -pthread -o a3p3Client2

a3p3Client3 : a3p3Client3.c
	gcc a3p3Client3.c -pthread -o a3p3Client3

a3p1Server : a3p1Server.c
	gcc a3p1Server.c -pthread -o a3p1Server

a3p2Server : a3p2Server.c
	gcc a3p2Server.c -pthread -o a3p2Server

a3p3Server : a3p3Server.c
	gcc a3p3Server.c -pthread -o a3p3Server
